/* Diagnostics: 0 */

/* Sources: 1 */
/* File Path: DUnion\DUnion.SourceGenerator\Valid.JsonValue.JsonValue.DUnion.g.cs */
// =============================================================
// This code was generated by the DUnion source generator.
// Changes to this file will be lost if the code is regenerated.
// =============================================================
#pragma warning disable
#nullable enable


namespace Valid.JsonValue
{
    partial record struct JsonValue
    {
        /// <summary>A value used to discriminate what this instance represents.</summary>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public global::System.Byte @Discriminator { get; }
    
        /// <summary>The underlying value this represents.</summary>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public global::System.Object? @UnderlyingValue { get; }
    
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        private JsonValue(global::System.Byte discriminator, global::System.Object? value)
        {
            this.@Discriminator = discriminator;
            this.@UnderlyingValue = value;
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="String"/>.
        /// </summary>
        /// <param name="value">The <see cref="String"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(String value) : this(1, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="Number"/>.
        /// </summary>
        /// <param name="value">The <see cref="Number"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(Number value) : this(2, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="Boolean"/>.
        /// </summary>
        /// <param name="value">The <see cref="Boolean"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(Boolean value) : this(3, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="Null"/>.
        /// </summary>
        /// <param name="value">The <see cref="Null"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(Null value) : this(4, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="Array"/>.
        /// </summary>
        /// <param name="value">The <see cref="Array"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(Array value) : this(5, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="JsonValue"/> which wraps a <see cref="Object"/>.
        /// </summary>
        /// <param name="value">The <see cref="Object"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public JsonValue(Object value) : this(6, value)
        {
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseString"/> if this is a <see cref="String"/></item>
        /// <item>Calls <paramref name="caseNumber"/> if this is a <see cref="Number"/></item>
        /// <item>Calls <paramref name="caseBoolean"/> if this is a <see cref="Boolean"/></item>
        /// <item>Calls <paramref name="caseNull"/> if this is a <see cref="Null"/></item>
        /// <item>Calls <paramref name="caseArray"/> if this is a <see cref="Array"/></item>
        /// <item>Calls <paramref name="caseObject"/> if this is a <see cref="Object"/></item>
        /// <item>Calls <paramref name="default"/> if the appropriate case* delegate wasnt provided.</item>
        /// </list>
        /// </summary>
        /// <param name="caseString">Called if this is a <see cref="String"/></param>
        /// <param name="caseNumber">Called if this is a <see cref="Number"/></param>
        /// <param name="caseBoolean">Called if this is a <see cref="Boolean"/></param>
        /// <param name="caseNull">Called if this is a <see cref="Null"/></param>
        /// <param name="caseArray">Called if this is a <see cref="Array"/></param>
        /// <param name="caseObject">Called if this is a <see cref="Object"/></param>
        /// <param name="default">Called if a delegate was not provided for this type</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Switch(global::System.Action @default, global::System.Action<String>? caseString = null, global::System.Action<Number>? caseNumber = null, global::System.Action<Boolean>? caseBoolean = null, global::System.Action<Null>? caseNull = null, global::System.Action<Array>? caseArray = null, global::System.Action<Object>? caseObject = null)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (!global::System.Object.ReferenceEquals(caseString, null))
                        caseString((String)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 2:
                    if (!global::System.Object.ReferenceEquals(caseNumber, null))
                        caseNumber((Number)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 3:
                    if (!global::System.Object.ReferenceEquals(caseBoolean, null))
                        caseBoolean((Boolean)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 4:
                    if (!global::System.Object.ReferenceEquals(caseNull, null))
                        caseNull((Null)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 5:
                    if (!global::System.Object.ReferenceEquals(caseArray, null))
                        caseArray((Array)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 6:
                    if (!global::System.Object.ReferenceEquals(caseObject, null))
                        caseObject((Object)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseString"/> if this is a <see cref="String"/></item>
        /// <item>Calls <paramref name="caseNumber"/> if this is a <see cref="Number"/></item>
        /// <item>Calls <paramref name="caseBoolean"/> if this is a <see cref="Boolean"/></item>
        /// <item>Calls <paramref name="caseNull"/> if this is a <see cref="Null"/></item>
        /// <item>Calls <paramref name="caseArray"/> if this is a <see cref="Array"/></item>
        /// <item>Calls <paramref name="caseObject"/> if this is a <see cref="Object"/></item>
        /// <item>Calls <paramref name="default"/> if the appropriate case* delegate wasnt provided.</item>
        /// </list>
        /// </summary>
        /// <param name="caseString">Called if this is a <see cref="String"/></param>
        /// <param name="caseNumber">Called if this is a <see cref="Number"/></param>
        /// <param name="caseBoolean">Called if this is a <see cref="Boolean"/></param>
        /// <param name="caseNull">Called if this is a <see cref="Null"/></param>
        /// <param name="caseArray">Called if this is a <see cref="Array"/></param>
        /// <param name="caseObject">Called if this is a <see cref="Object"/></param>
        /// <param name="default">Called if a delegate was not provided for this type</param>
        /// <returns>The value returned from the matched delegate</returns>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public TMatchResult Match<TMatchResult>(global::System.Func<TMatchResult> @default, global::System.Func<String, TMatchResult>? caseString = null, global::System.Func<Number, TMatchResult>? caseNumber = null, global::System.Func<Boolean, TMatchResult>? caseBoolean = null, global::System.Func<Null, TMatchResult>? caseNull = null, global::System.Func<Array, TMatchResult>? caseArray = null, global::System.Func<Object, TMatchResult>? caseObject = null)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (!global::System.Object.ReferenceEquals(caseString, null))
                        return caseString((String)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 2:
                    if (!global::System.Object.ReferenceEquals(caseNumber, null))
                        return caseNumber((Number)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 3:
                    if (!global::System.Object.ReferenceEquals(caseBoolean, null))
                        return caseBoolean((Boolean)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 4:
                    if (!global::System.Object.ReferenceEquals(caseNull, null))
                        return caseNull((Null)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 5:
                    if (!global::System.Object.ReferenceEquals(caseArray, null))
                        return caseArray((Array)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 6:
                    if (!global::System.Object.ReferenceEquals(caseObject, null))
                        return caseObject((Object)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseString"/> if this is a <see cref="String"/></item>
        /// <item>Calls <paramref name="caseNumber"/> if this is a <see cref="Number"/></item>
        /// <item>Calls <paramref name="caseBoolean"/> if this is a <see cref="Boolean"/></item>
        /// <item>Calls <paramref name="caseNull"/> if this is a <see cref="Null"/></item>
        /// <item>Calls <paramref name="caseArray"/> if this is a <see cref="Array"/></item>
        /// <item>Calls <paramref name="caseObject"/> if this is a <see cref="Object"/></item>
        /// </list>
        /// </summary>
        /// <param name="caseString">Called if this is a <see cref="String"/></param>
        /// <param name="caseNumber">Called if this is a <see cref="Number"/></param>
        /// <param name="caseBoolean">Called if this is a <see cref="Boolean"/></param>
        /// <param name="caseNull">Called if this is a <see cref="Null"/></param>
        /// <param name="caseArray">Called if this is a <see cref="Array"/></param>
        /// <param name="caseObject">Called if this is a <see cref="Object"/></param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Switch(global::System.Action<String> caseString, global::System.Action<Number> caseNumber, global::System.Action<Boolean> caseBoolean, global::System.Action<Null> caseNull, global::System.Action<Array> caseArray, global::System.Action<Object> caseObject)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (global::System.Object.ReferenceEquals(caseString, null))
                        throw new global::System.ArgumentNullException(nameof(caseString));
                    caseString((String)this.@UnderlyingValue!);
                    break;
                case 2:
                    if (global::System.Object.ReferenceEquals(caseNumber, null))
                        throw new global::System.ArgumentNullException(nameof(caseNumber));
                    caseNumber((Number)this.@UnderlyingValue!);
                    break;
                case 3:
                    if (global::System.Object.ReferenceEquals(caseBoolean, null))
                        throw new global::System.ArgumentNullException(nameof(caseBoolean));
                    caseBoolean((Boolean)this.@UnderlyingValue!);
                    break;
                case 4:
                    if (global::System.Object.ReferenceEquals(caseNull, null))
                        throw new global::System.ArgumentNullException(nameof(caseNull));
                    caseNull((Null)this.@UnderlyingValue!);
                    break;
                case 5:
                    if (global::System.Object.ReferenceEquals(caseArray, null))
                        throw new global::System.ArgumentNullException(nameof(caseArray));
                    caseArray((Array)this.@UnderlyingValue!);
                    break;
                case 6:
                    if (global::System.Object.ReferenceEquals(caseObject, null))
                        throw new global::System.ArgumentNullException(nameof(caseObject));
                    caseObject((Object)this.@UnderlyingValue!);
                    break;
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseString"/> if this is a <see cref="String"/></item>
        /// <item>Calls <paramref name="caseNumber"/> if this is a <see cref="Number"/></item>
        /// <item>Calls <paramref name="caseBoolean"/> if this is a <see cref="Boolean"/></item>
        /// <item>Calls <paramref name="caseNull"/> if this is a <see cref="Null"/></item>
        /// <item>Calls <paramref name="caseArray"/> if this is a <see cref="Array"/></item>
        /// <item>Calls <paramref name="caseObject"/> if this is a <see cref="Object"/></item>
        /// </list>
        /// </summary>
        /// <param name="caseString">Called if this is a <see cref="String"/></param>
        /// <param name="caseNumber">Called if this is a <see cref="Number"/></param>
        /// <param name="caseBoolean">Called if this is a <see cref="Boolean"/></param>
        /// <param name="caseNull">Called if this is a <see cref="Null"/></param>
        /// <param name="caseArray">Called if this is a <see cref="Array"/></param>
        /// <param name="caseObject">Called if this is a <see cref="Object"/></param>
        /// <returns>The value returned from the matched delegate</returns>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public TMatchResult Match<TMatchResult>(global::System.Func<String, TMatchResult> caseString, global::System.Func<Number, TMatchResult> caseNumber, global::System.Func<Boolean, TMatchResult> caseBoolean, global::System.Func<Null, TMatchResult> caseNull, global::System.Func<Array, TMatchResult> caseArray, global::System.Func<Object, TMatchResult> caseObject)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (global::System.Object.ReferenceEquals(caseString, null))
                        throw new global::System.ArgumentNullException(nameof(caseString));
                    return caseString((String)this.@UnderlyingValue!);
                case 2:
                    if (global::System.Object.ReferenceEquals(caseNumber, null))
                        throw new global::System.ArgumentNullException(nameof(caseNumber));
                    return caseNumber((Number)this.@UnderlyingValue!);
                case 3:
                    if (global::System.Object.ReferenceEquals(caseBoolean, null))
                        throw new global::System.ArgumentNullException(nameof(caseBoolean));
                    return caseBoolean((Boolean)this.@UnderlyingValue!);
                case 4:
                    if (global::System.Object.ReferenceEquals(caseNull, null))
                        throw new global::System.ArgumentNullException(nameof(caseNull));
                    return caseNull((Null)this.@UnderlyingValue!);
                case 5:
                    if (global::System.Object.ReferenceEquals(caseArray, null))
                        throw new global::System.ArgumentNullException(nameof(caseArray));
                    return caseArray((Array)this.@UnderlyingValue!);
                case 6:
                    if (global::System.Object.ReferenceEquals(caseObject, null))
                        throw new global::System.ArgumentNullException(nameof(caseObject));
                    return caseObject((Object)this.@UnderlyingValue!);
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        
        /// <summary>
        /// If the current value is a <see cref="String"/> then <paramref name="asString"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="String"/> will be set to <c>default(<see cref="String"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asString">The current value if this is a <see cref="String"/>, otherwise <c>default(<see cref="String"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="String"/>, otherwise <c>false</c></returns>
        public bool IsString([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out String asString)
        {
            if (this.@Discriminator != 1)
            {
                asString = default(String);
                return false;
            }
            asString = (String)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="Number"/> then <paramref name="asNumber"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Number"/> will be set to <c>default(<see cref="Number"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asNumber">The current value if this is a <see cref="Number"/>, otherwise <c>default(<see cref="Number"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Number"/>, otherwise <c>false</c></returns>
        public bool IsNumber([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Number asNumber)
        {
            if (this.@Discriminator != 2)
            {
                asNumber = default(Number);
                return false;
            }
            asNumber = (Number)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="Boolean"/> then <paramref name="asBoolean"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Boolean"/> will be set to <c>default(<see cref="Boolean"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asBoolean">The current value if this is a <see cref="Boolean"/>, otherwise <c>default(<see cref="Boolean"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Boolean"/>, otherwise <c>false</c></returns>
        public bool IsBoolean([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Boolean asBoolean)
        {
            if (this.@Discriminator != 3)
            {
                asBoolean = default(Boolean);
                return false;
            }
            asBoolean = (Boolean)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="Null"/> then <paramref name="asNull"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Null"/> will be set to <c>default(<see cref="Null"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asNull">The current value if this is a <see cref="Null"/>, otherwise <c>default(<see cref="Null"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Null"/>, otherwise <c>false</c></returns>
        public bool IsNull([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Null asNull)
        {
            if (this.@Discriminator != 4)
            {
                asNull = default(Null);
                return false;
            }
            asNull = (Null)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="Array"/> then <paramref name="asArray"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Array"/> will be set to <c>default(<see cref="Array"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asArray">The current value if this is a <see cref="Array"/>, otherwise <c>default(<see cref="Array"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Array"/>, otherwise <c>false</c></returns>
        public bool IsArray([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Array asArray)
        {
            if (this.@Discriminator != 5)
            {
                asArray = default(Array);
                return false;
            }
            asArray = (Array)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="Object"/> then <paramref name="asObject"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Object"/> will be set to <c>default(<see cref="Object"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asObject">The current value if this is a <see cref="Object"/>, otherwise <c>default(<see cref="Object"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Object"/>, otherwise <c>false</c></returns>
        public bool IsObject([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Object asObject)
        {
            if (this.@Discriminator != 6)
            {
                asObject = default(Object);
                return false;
            }
            asObject = (Object)this.@UnderlyingValue;
            return true;
        }
        
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(String value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator String(JsonValue value)
        {
            if (value.@Discriminator != 1)
                throw new global::System.InvalidCastException();
            return (String)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(Number value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Number(JsonValue value)
        {
            if (value.@Discriminator != 2)
                throw new global::System.InvalidCastException();
            return (Number)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(Boolean value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Boolean(JsonValue value)
        {
            if (value.@Discriminator != 3)
                throw new global::System.InvalidCastException();
            return (Boolean)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(Null value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Null(JsonValue value)
        {
            if (value.@Discriminator != 4)
                throw new global::System.InvalidCastException();
            return (Null)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(Array value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Array(JsonValue value)
        {
            if (value.@Discriminator != 5)
                throw new global::System.InvalidCastException();
            return (Array)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator JsonValue(Object value)
        {
            return new JsonValue(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Object(JsonValue value)
        {
            if (value.@Discriminator != 6)
                throw new global::System.InvalidCastException();
            return (Object)value.@UnderlyingValue!;
        }
    }
}