/* Diagnostics: 0 */

/* Sources: 1 */
/* File Path: DUnion\DUnion.SourceGenerator\Valid.Option.Option`1.DUnion.g.cs */
// =============================================================
// This code was generated by the DUnion source generator.
// Changes to this file will be lost if the code is regenerated.
// =============================================================
#pragma warning disable
#nullable enable


namespace Valid.Option
{
    partial record struct Option<T>
    {
        /// <summary>A value used to discriminate what this instance represents.</summary>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public global::System.Byte @Discriminator { get; }
    
        /// <summary>The underlying value this represents.</summary>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public global::System.Object? @UnderlyingValue { get; }
    
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        private Option(global::System.Byte discriminator, global::System.Object? value)
        {
            this.@Discriminator = discriminator;
            this.@UnderlyingValue = value;
        }
        
        /// <summary>
        /// Creates a <see cref="Option{T}"/> which wraps a <see cref="Some"/>.
        /// </summary>
        /// <param name="value">The <see cref="Some"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public Option(Some value) : this(1, value)
        {
        }
        
        /// <summary>
        /// Creates a <see cref="Option{T}"/> which wraps a <see cref="None"/>.
        /// </summary>
        /// <param name="value">The <see cref="None"/> to wrap</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public Option(None value) : this(2, value)
        {
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseSome"/> if this is a <see cref="Some"/></item>
        /// <item>Calls <paramref name="caseNone"/> if this is a <see cref="None"/></item>
        /// <item>Calls <paramref name="default"/> if the appropriate case* delegate wasnt provided.</item>
        /// </list>
        /// </summary>
        /// <param name="caseSome">Called if this is a <see cref="Some"/></param>
        /// <param name="caseNone">Called if this is a <see cref="None"/></param>
        /// <param name="default">Called if a delegate was not provided for this type</param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Switch(global::System.Action @default, global::System.Action<Some>? caseSome = null, global::System.Action<None>? caseNone = null)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (!global::System.Object.ReferenceEquals(caseSome, null))
                        caseSome((Some)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                case 2:
                    if (!global::System.Object.ReferenceEquals(caseNone, null))
                        caseNone((None)this.@UnderlyingValue!);
                    else if (!global::System.Object.ReferenceEquals(@default, null))
                        @default();
                    else
                        throw new global::System.ArgumentNullException(nameof(@default));
                    break;
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseSome"/> if this is a <see cref="Some"/></item>
        /// <item>Calls <paramref name="caseNone"/> if this is a <see cref="None"/></item>
        /// <item>Calls <paramref name="default"/> if the appropriate case* delegate wasnt provided.</item>
        /// </list>
        /// </summary>
        /// <param name="caseSome">Called if this is a <see cref="Some"/></param>
        /// <param name="caseNone">Called if this is a <see cref="None"/></param>
        /// <param name="default">Called if a delegate was not provided for this type</param>
        /// <returns>The value returned from the matched delegate</returns>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public TMatchResult Match<TMatchResult>(global::System.Func<TMatchResult> @default, global::System.Func<Some, TMatchResult>? caseSome = null, global::System.Func<None, TMatchResult>? caseNone = null)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (!global::System.Object.ReferenceEquals(caseSome, null))
                        return caseSome((Some)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                case 2:
                    if (!global::System.Object.ReferenceEquals(caseNone, null))
                        return caseNone((None)this.@UnderlyingValue!);
                    if (!global::System.Object.ReferenceEquals(@default, null))
                        return @default();
                    throw new global::System.ArgumentNullException(nameof(@default));
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseSome"/> if this is a <see cref="Some"/></item>
        /// <item>Calls <paramref name="caseNone"/> if this is a <see cref="None"/></item>
        /// </list>
        /// </summary>
        /// <param name="caseSome">Called if this is a <see cref="Some"/></param>
        /// <param name="caseNone">Called if this is a <see cref="None"/></param>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Switch(global::System.Action<Some> caseSome, global::System.Action<None> caseNone)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (global::System.Object.ReferenceEquals(caseSome, null))
                        throw new global::System.ArgumentNullException(nameof(caseSome));
                    caseSome((Some)this.@UnderlyingValue!);
                    break;
                case 2:
                    if (global::System.Object.ReferenceEquals(caseNone, null))
                        throw new global::System.ArgumentNullException(nameof(caseNone));
                    caseNone((None)this.@UnderlyingValue!);
                    break;
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        /// <summary>
        /// Calls the appropriate delegate for the current type.
        /// <list type="bullet">
        /// <item>Calls <paramref name="caseSome"/> if this is a <see cref="Some"/></item>
        /// <item>Calls <paramref name="caseNone"/> if this is a <see cref="None"/></item>
        /// </list>
        /// </summary>
        /// <param name="caseSome">Called if this is a <see cref="Some"/></param>
        /// <param name="caseNone">Called if this is a <see cref="None"/></param>
        /// <returns>The value returned from the matched delegate</returns>
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public TMatchResult Match<TMatchResult>(global::System.Func<Some, TMatchResult> caseSome, global::System.Func<None, TMatchResult> caseNone)
        {
            switch (this.@Discriminator)
            {
                case 0:
                    throw new global::System.InvalidOperationException("Union has not been initialized");
                case 1:
                    if (global::System.Object.ReferenceEquals(caseSome, null))
                        throw new global::System.ArgumentNullException(nameof(caseSome));
                    return caseSome((Some)this.@UnderlyingValue!);
                case 2:
                    if (global::System.Object.ReferenceEquals(caseNone, null))
                        throw new global::System.ArgumentNullException(nameof(caseNone));
                    return caseNone((None)this.@UnderlyingValue!);
                default:
                    throw new global::System.InvalidOperationException($"Unsupported discriminator value {Discriminator}");
            }
        }
    
        
        /// <summary>
        /// If the current value is a <see cref="Some"/> then <paramref name="asSome"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="Some"/> will be set to <c>default(<see cref="Some"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asSome">The current value if this is a <see cref="Some"/>, otherwise <c>default(<see cref="Some"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="Some"/>, otherwise <c>false</c></returns>
        public bool IsSome([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out Some asSome)
        {
            if (this.@Discriminator != 1)
            {
                asSome = default(Some);
                return false;
            }
            asSome = (Some)this.@UnderlyingValue;
            return true;
        }
        
        /// <summary>
        /// If the current value is a <see cref="None"/> then <paramref name="asNone"/> will be set to it and <c>true</c> will be returned,
        /// otherwise <paramref name="None"/> will be set to <c>default(<see cref="None"/>)</c> and <c>false</c> will be returned
        /// </summary>
        /// <param name="asNone">The current value if this is a <see cref="None"/>, otherwise <c>default(<see cref="None"/>)</c></param>
        /// <returns><c>true</c> if the current value is a <see cref="None"/>, otherwise <c>false</c></returns>
        public bool IsNone([global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(true)]out None asNone)
        {
            if (this.@Discriminator != 2)
            {
                asNone = default(None);
                return false;
            }
            asNone = (None)this.@UnderlyingValue;
            return true;
        }
        
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator Option<T>(Some value)
        {
            return new Option<T>(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator Some(Option<T> value)
        {
            if (value.@Discriminator != 1)
                throw new global::System.InvalidCastException();
            return (Some)value.@UnderlyingValue!;
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static implicit operator Option<T>(None value)
        {
            return new Option<T>(value);
        }
        
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static explicit operator None(Option<T> value)
        {
            if (value.@Discriminator != 2)
                throw new global::System.InvalidCastException();
            return (None)value.@UnderlyingValue!;
        }
    }
}