namespace DUnion.Models;

internal static class Constants
{
    public const string AutoGeneratedHeader = """
        // =============================================================
        // This code was generated by the DUnion source generator.
        // Changes to this file will be lost if the code is regenerated.
        // =============================================================
        """;

    public const string DUnionDiscriminator = "DiscriminatorName";
    public const string DUnionIsCase = "IsCase";
    public const string DUnionMatch = "Match";
    public const string DUnionSwitch = "Switch";
    public const string DUnionUnderlyingValue = "ValueName";
    public static readonly string DUnionExcludeFullName = "DUnion.DUnionExcludeAttribute";
    public static readonly string DUnionFullName = "DUnion.DUnionAttribute";
}