namespace DUnion.Models;

internal static class Constants
{
    public const string AutoGeneratedHeader = """
        // =============================================================
        // This code was generated by the DUnion source generator.
        // Changes to this file will be lost if the code is regenerated.
        // =============================================================

        """;

    public const string CaseOrDefaultName = "CaseOrDefaultName";
    public const string DiscriminatorName = "DiscriminatorName";
    public const string DUnionAttribute = "DUnion.DUnionAttribute";
    public const string DUnionCaseAttribute = "DUnion.DUnionCaseAttribute";
    public const string DUnionCaseExcludeAttribute = "DUnion.DUnionExcludeAttribute";
    public const string DUnionGenericAttribute = "DUnion.DUnionGenericAttribute";
    public const string IsCaseName = "IsCaseName";
    public const string MatchName = "MatchName";
    public const string SwitchName = "SwitchName";
    public const string UseUnsafe = "UseUnsafe";
    public const string ValueName = "ValueName";
}